dependencies:
- nodejs==15.*
- python==3.10.*

- jupyterlab
- jupyterhub-singleuser>3.0<4.0
- matplotlib
- ipympl
- pandas
- scipy
- statsmodels
- seaborn

# Items not in conda forge
- pip
- pip:
  - folium
  - okpy
  - datascience
  - otter-grader
